require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe PriceModelsController do

  # This should return the minimal set of attributes required to create a valid
  # PriceModel. As you add validations to PriceModel, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { "agency_id" => "1" }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # PriceModelsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all price_models as @price_models" do
      price_model = PriceModel.create! valid_attributes
      get :index, {}, valid_session
      assigns(:price_models).should eq([price_model])
    end
  end

  describe "GET show" do
    it "assigns the requested price_model as @price_model" do
      price_model = PriceModel.create! valid_attributes
      get :show, {:id => price_model.to_param}, valid_session
      assigns(:price_model).should eq(price_model)
    end
  end

  describe "GET new" do
    it "assigns a new price_model as @price_model" do
      get :new, {}, valid_session
      assigns(:price_model).should be_a_new(PriceModel)
    end
  end

  describe "GET edit" do
    it "assigns the requested price_model as @price_model" do
      price_model = PriceModel.create! valid_attributes
      get :edit, {:id => price_model.to_param}, valid_session
      assigns(:price_model).should eq(price_model)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new PriceModel" do
        expect {
          post :create, {:price_model => valid_attributes}, valid_session
        }.to change(PriceModel, :count).by(1)
      end

      it "assigns a newly created price_model as @price_model" do
        post :create, {:price_model => valid_attributes}, valid_session
        assigns(:price_model).should be_a(PriceModel)
        assigns(:price_model).should be_persisted
      end

      it "redirects to the created price_model" do
        post :create, {:price_model => valid_attributes}, valid_session
        response.should redirect_to(PriceModel.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved price_model as @price_model" do
        # Trigger the behavior that occurs when invalid params are submitted
        PriceModel.any_instance.stub(:save).and_return(false)
        post :create, {:price_model => { "agency_id" => "invalid value" }}, valid_session
        assigns(:price_model).should be_a_new(PriceModel)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        PriceModel.any_instance.stub(:save).and_return(false)
        post :create, {:price_model => { "agency_id" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested price_model" do
        price_model = PriceModel.create! valid_attributes
        # Assuming there are no other price_models in the database, this
        # specifies that the PriceModel created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        PriceModel.any_instance.should_receive(:update).with({ "agency_id" => "1" })
        put :update, {:id => price_model.to_param, :price_model => { "agency_id" => "1" }}, valid_session
      end

      it "assigns the requested price_model as @price_model" do
        price_model = PriceModel.create! valid_attributes
        put :update, {:id => price_model.to_param, :price_model => valid_attributes}, valid_session
        assigns(:price_model).should eq(price_model)
      end

      it "redirects to the price_model" do
        price_model = PriceModel.create! valid_attributes
        put :update, {:id => price_model.to_param, :price_model => valid_attributes}, valid_session
        response.should redirect_to(price_model)
      end
    end

    describe "with invalid params" do
      it "assigns the price_model as @price_model" do
        price_model = PriceModel.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        PriceModel.any_instance.stub(:save).and_return(false)
        put :update, {:id => price_model.to_param, :price_model => { "agency_id" => "invalid value" }}, valid_session
        assigns(:price_model).should eq(price_model)
      end

      it "re-renders the 'edit' template" do
        price_model = PriceModel.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        PriceModel.any_instance.stub(:save).and_return(false)
        put :update, {:id => price_model.to_param, :price_model => { "agency_id" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested price_model" do
      price_model = PriceModel.create! valid_attributes
      expect {
        delete :destroy, {:id => price_model.to_param}, valid_session
      }.to change(PriceModel, :count).by(-1)
    end

    it "redirects to the price_models list" do
      price_model = PriceModel.create! valid_attributes
      delete :destroy, {:id => price_model.to_param}, valid_session
      response.should redirect_to(price_models_url)
    end
  end

end
